---
version: '3'

services:

  app:
    build: .
    depends_on:
      - database
      - netbox
    environment:
      - NETBOX_API_URL=${NETBOX_API_URL-http://netbox:8000/api}
      - NETBOX_API_TOKEN=${NETBOX_API_TOKEN-0123456789abcdef0123456789abcdef01234567}
    env_file:
      - .defaults.env
      - .user-settings.env
    ports:
      - 8888:8000
    volumes:
      - .:/usr/src/app:ro
    entrypoint: ../../apps_dev/dev-entrypoint.sh
    command: "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=netdash
      - POSTGRES_DB=netdash
    volumes:
      - netdash-postgres-data:/var/lib/postgresql/data

  netbox:
    image: netboxcommunity/netbox:${NETBOX_VERSION-latest}
    depends_on:
      - netbox-database
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=12345
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_HOST=netbox-database
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin
      - SUPERUSER_API_TOKEN=0123456789abcdef0123456789abcdef01234567
    ports:
      - 8000:8000

  netbox-database:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=netbox
      - POSTGRES_DB=netbox
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

volumes:
  netdash-postgres-data:
  netbox-postgres-data:
  migrator-home-dir:
